@startuml
'https://plantuml.com/class-diagram

class Employee {
    __ private data__
    - string firstName
    - string lastName
    - string socialSecurityNumber

    ..Public Accessors..
    + string getFirstName()
    + string getLastName()
    + string getSocialSecurityNumber()

    ..Public Mutators..
    + void setFirstName()
    + void setLastName()
    + void setSocialSecurityNumber()

    ..String Method..
    + string toString()
}

class SalariedEmployee extends Employee {
    __Data__
    + int weeklySalary

    ..Public Accessors..
    + int getWeeklySalary()

    ..Public Mutators..
    + void setWeeklySalary()

    ..String Method..
    + string toString()
}

class HourlyEmployee extends Employee {
    __Data__
    + int wage
    + int hoursWorked

    ..Public Accessors..
    + int getWage()
    + int getHoursWorked()

    ..Public Mutators..
    + void setWage()
    + void setHoursWorked()

    ..String Method..
    + string toString()
}

class CommissionEmployee extends Employee {
    __Data__
    + int commissionRate
    + int grossSales

    ..Public Accessors..
    + int getCommissionRate()
    + int getGrossSales()

    ..Public Mutators..
    + void setCommissionRate()
    + void setGrossSales()

    ..String Method..
    + string toString()
}

class BaseEmployee extends Employee {
    __Data__
    + int baseSalary

    ..Public Accessors..
    + int getBaseSalary()

    ..Public Mutators..
    + void setBaseSalary()

    ..String Method..
    + string toString()
}

class Driver {
    + void main(String[])
}

Driver --> Employee

@enduml