@startuml
'https://plantuml.com/class-diagram

class Ship {
    --Protected Data--
    # string shipName
    # string yearBuilt

    ..Public Accessors..
    + string getShipName()
    + string getYearBuilt()

    ..Public Mutators..
    + void setShipName()
    + void setYearBuilt()

    ..String Method..
    + string toString()

    ..Print Method..
    + void printShip()
}

class CargoShip extends Ship {
    __ Data __
    + int cargoCapacityInTonnage

    ..Public Accessors..
    + int getCargoCapacityInTonnage()

    ..Public Mutators..
    + void setCargoCapacityInTonnage()

    ..String Method..
    + string toString()
}

class CruiseShip extends Ship {
    __ Data __
    + int maxNumberPassengers

    ..Public Accessors..
    + int getMaxNumberPassengers()

    ..Public Mutators..
    + void setMaxNumberPassengers()

    ..String Method..
    + string toString()
}

class Driver {
    + void main(String[] args)
}

Driver --> Ship

@enduml